compose:
  "Abstention"           : "abstention"
  "Generalization"       : "generalization"
  "Specificity"          : "specificity"
  # "Specificity (Easy)"   : "specificity.easy"
  # "Atomic Generalization": "generalization.atomic"
  # "Atomic Specificity"   : "specificity.atomic"
  # "Unrelated"            : "unrelated"

atom:
  "Abstention"    : "abstention"
  "Generalization": "generalization"
  "Specificity"   : "specificity"
  # "Unrelated"     : "unrelated"